//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirLineManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class VD3
    {
        public string To { get; set; }
        public string FlightNumber { get; set; }
        public int AircraftID { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public int ID { get; set; }
        public decimal EconomyPrice { get; set; }
        public int DepartureAirportID { get; set; }
        public int ArrivalAirportID { get; set; }
        public bool Confirmed { get; set; }
        public int Distance { get; set; }
    }
}
