//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirLineManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class VD4
    {
        public string From { get; set; }
        public int ID { get; set; }
        public decimal EconomyPrice { get; set; }
        public int DepartureAirportID { get; set; }
        public int ArrivalAirportID { get; set; }
    }
}
